///////////////////////////////////////////////////////////
//  AcademicRecord.cs
//  Implementation of the Class AcademicRecord
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AcademicRecord {

	private int completedCreditHours;
	private decimal gpa;
	private int recordId;
	private int studentId;
	private int totalCreditHours;

	public AcademicRecord(){

	}

	~AcademicRecord(){

	}

	public decimal CalculateGPA(){

		return 0;
	}

	public List<Enrollment> GetCompletedCourses(){

		return null;
	}

	public List<Enrollment> GetInProgressCoureses(){

		return null;
	}

	public string GetTranscript(){

		return "";
	}

}//end AcademicRecord