///////////////////////////////////////////////////////////
//  Adviser.cs
//  Implementation of the Class Adviser
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Adviser : User {

	private int adviserId;
	private string department;
	private string facultyId;
	private string officeLocation;
	public Report m_Report;

	public Adviser(){

	}

	~Adviser(){

	}

	/// 
	/// <param name="studentId"></param>
	public AcademicRecord AccessAcademicHistory(int studentId){

		return null;
	}

	/// 
	/// <param name="enrollmentId"></param>
	public void ApproveCoursePlan(int enrollmentId){

	}

	/// 
	/// <param name="studentId"></param>
	public Report GenerateProgressReport(int studentId){

		return null;
	}

	public bool Login(){

		return false;
	}

	public void Logout(){

	}

	/// 
	/// <param name="enrollmentId"></param>
	public void ModifyCoursePlan(int enrollmentId){

	}

	/// 
	/// <param name="studentId"></param>
	public void RecommebdCourses(int studentId){

	}

	public void UpdateProfile(){

	}

	public List<Student> ViewAssignedAdvisees(){

		return null;
	}

}//end Adviser