///////////////////////////////////////////////////////////
//  Corequisite.cs
//  Implementation of the Class Corequisite
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Corequisite {

	private int corequisiteCourseId;
	private int corequisiteId;
	private int courseId;
	public Course m_Course;

	public Corequisite(){

	}

	~Corequisite(){

	}

	/// 
	/// <param name="studentId"></param>
	public bool ValidateCorequisite(int studentId){

		return false;
	}

}//end Corequisite