///////////////////////////////////////////////////////////
//  Course.cs
//  Implementation of the Class Course
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Course {

	private string courseCode;
	private int courseId;
	private string courseName;
	private string courseType;
	private int creditHours;
	private string description;
	private int specializationId;
	public Corequisite m_Corequisite;
	public Specialization m_Specialization;
	public Prerequisite m_Prerequisite;

	public Course(){

	}

	~Course(){

	}

	/// 
	/// <param name="studentId"></param>
	public bool CheckEligibility(int studentId){

		return false;
	}

	public List<Course> GetCorequisites(){

		return null;
	}

	public List<Course> GetPrerequisites(){

		return null;
	}

}//end Course