///////////////////////////////////////////////////////////
//  Enrollment.cs
//  Implementation of the Class Enrollment
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Enrollment {

	private string adviserRemarks;
	private string approvalStatus;
	private int courseId;
	private Date enrollmentDate;
	private int enrollmentId;
	private string grade;
	private int semesterId;
	private string status;
	private int studentId;
	public Course m_Course;
	public Semester m_Semester;

	public Enrollment(){

	}

	~Enrollment(){

	}

	public void ApproveEnrollment(){

	}

	/// 
	/// <param name="reason"></param>
	public void RejectEnrollment(string reason){

	}

	public void SubmitForApproval(){

	}

}//end Enrollment