///////////////////////////////////////////////////////////
//  Prerequisite.cs
//  Implementation of the Class Prerequisite
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Prerequisite {

	private int courseId;
	private bool isStrict;
	private int prerequisiteCourseId;
	private int prerequisiteId;
	public Course m_Course;

	public Prerequisite(){

	}

	~Prerequisite(){

	}

}//end Prerequisite