///////////////////////////////////////////////////////////
//  Report.cs
//  Implementation of the Class Report
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Report {

	private string content;
	private int generateBy;
	private Date generateDate;
	private int reportId;
	private string reportType;

	public Report(){

	}

	~Report(){

	}

	public void ExportToPDF(){

	}

	public void GenerateProgressReport(){

	}

}//end Report