///////////////////////////////////////////////////////////
//  Semester.cs
//  Implementation of the Class Semester
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Semester {

	private string academicYear;
	private DateTime endDate;
	private bool isActive;
	private int semesterId;
	private string semesterName;
	private DateTime startDate;
	public SemesterOffering m_SemesterOffering;

	public Semester(){

	}

	~Semester(){

	}

	public List<Course> GetOfferedCourses(){

		return null;
	}

}//end Semester