///////////////////////////////////////////////////////////
//  SemesterOffering.cs
//  Implementation of the Class SemesterOffering
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SemesterOffering {

	private int courseId;
	private int currentEnrollment;
	private int maxCapacity;
	private int offeringId;
	private int semesterId;
	public Course m_Course;

	public SemesterOffering(){

	}

	~SemesterOffering(){

	}

	public bool isAvailable(){

		return false;
	}

}//end SemesterOffering