///////////////////////////////////////////////////////////
//  Specialization.cs
//  Implementation of the Class Specialization
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Specialization {

	private string description;
	private int requiredCreditHours;
	private int specializationId;
	private string specializationName;

	public Specialization(){

	}

	~Specialization(){

	}

	public List<Course> GetCoreSubjects(){

		return null;
	}

	public string GetCurriculumFlowchart(){

		return "";
	}

	public List<Course> GetSpecializedSubjects(){

		return null;
	}

}//end Specialization