///////////////////////////////////////////////////////////
//  Student.cs
//  Implementation of the Class Student
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Student : User {

	private int currentSemester;
	private int enrollmentYear;
	private int gpa;
	private int specializationId;
	private int studentId;
	private string studentNumber;
	public Adviser m_Adviser;
	public AcademicRecord m_AcademicRecord;
	public Specialization m_Specialization;

	public Student(){

	}

	~Student(){

	}

	public bool Login(){

		return false;
	}

	public void Logout(){

	}

	public void SubmitCoursePreferences(){

	}

	public void UpdateProfile(){

	}

	public AcademicRecord ViewAcademicRecord(){

		return null;
	}

	public List<string> ViewAdviserRemarks(){

		return null;
	}

	public List<Enrollment> ViewApprovedCourses(){

		return null;
	}

	public List<Course> ViewEligibleCourses(){

		return null;
	}

}//end Student