///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2025 4:19:13 AM
//  Original author: ahmed-pc
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class User {

	private DateTime createdAt;
	private string email;
	private DateTime lastLogin;
	private string password;
	private string role;
	private int userId;
	private string username;

	public User(){

	}

	~User(){

	}

	public bool Login(){

		return false;
	}

	public void Logout(){

	}

	public void UpdateProfile(){

	}

}//end User